### ISSUE TITLE
Restrict behaves like ClientSetNull in EF Core 2.2 Npgsql

### ISSUE THREAD

**Issue by ArthDevRepo** [aspnet/EntityFramework.Docs.pt-br#16]
I`m using EF Core 2.2 and when i set Delete Behaivor in a relationship to Restrict, the foreign key is set to null in tracked entities when they are made orphans. This is not in accordance with the behavior described in this article: do not set foreign key property in the child entity to null.

Source code in:
https://github.com/ArthDevRepo/EfCoreRestrictBehaivorProblem

Expected behaivor: When Restrict, do not set FK Property to NULL
Actual behaivor: When Restrict, set FK Property to NULL.

Thanks
---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 3ed1b8a1-fa32-e147-ae0f-76b3620473f9
* Version Independent ID: 10ce2d9f-8284-a509-5fed-669abfb9d8ae
* Content: [Excluir em cascata – EF Core](https://docs.microsoft.com/pt-br/ef/core/saving/cascade-delete#feedback)
* Content Source: [entity-framework/core/saving/cascade-delete.md](https://github.com/aspnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/core/saving/cascade-delete.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @rowanmiller
* Microsoft Alias: **divega**

**Comment by lichasu** [comment]
Hello, @ArthDevRepo ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
