### ISSUE TITLE
Não consigo habilitar Migrations Visual Studio 2019

### ISSUE THREAD

**Issue by fioravante-joao** [aspnet/EntityFramework.Docs.pt-br#17]
[Estou Usando VisualStudio 2019 e não consigo habilitar Migrations, pois a seguinte mensagem é apresentada. 
Enable-Migrations : Não é possível associar o argumento ao parâmetro 'Path' porque ele é nulo.
No linha:1 caractere:1
+ Enable-Migrations
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Enable-Migrations], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Enable-Migrations
]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 002d162b-8595-ad48-7ef8-2cd10194a3b4
* Version Independent ID: a29d6e0c-f9eb-86d9-f82e-0e9fc41b5a0d
* Content: [Migrações do Code First – EF6](https://docs.microsoft.com/pt-br/ef/ef6/modeling/code-first/migrations/index?redirectedfrom=MSDN#feedback)
* Content Source: [entity-framework/ef6/modeling/code-first/migrations/index.md](https://github.com/aspnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/ef6/modeling/code-first/migrations/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-6**
* GitHub Login: @divega
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @fioravante-joao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @fioravante-joao 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
