### ISSUE TITLE
Reinserir na documentação o uso de EF Core em projetos UWP

### ISSUE THREAD

**Issue by joaosantana** [aspnet/EntityFramework.Docs.pt-br#18]
Ao adaptar os passos descritos numa solução com um projeto UWP e um projeto .NET Standard para a lógica do programa, ao rodar `Add-Migration InitialMigrate` recebe-se a seguinte mensagem de erro:

`Startup project 'Recibos' is a Universal Windows Platform app. This version of the Entity Framework Core Package Manager Console Tools doesn't support this type of project. For more information on using the EF Core Tools with UWP projects, see https://go.microsoft.com/fwlink/?linkid=858496`

A página referenciada é esta mesma, sem que haja qualquer informação sobre como usar as ferramentas EF Core com projetos UWP. como a mensagem de erro informa.

Alterar o projeto de inicialização para o projeto .NET Standard e rodar o mesmo comando retorna a seguinte mensagem de erro:

`Startup project 'Recibos.Core' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core Package Manager Console Tools with this project, add an executable project targeting .NET Framework or .NET Core that references this project, and set it as the startup project; or, update this project to cross-target .NET Framework or .NET Core. For more information on using the EF Core Tools with .NET Standard projects, see https://go.microsoft.com/fwlink/?linkid=2034705`

Dessa vez, o link referenciado possui informação sensitiva sobre o problema, que é a inexistência de um projeto de console cuja função seja de ser usado para executar as ferramentas. Este esquema era descrito em https://docs.microsoft.com/ef/core/get-started/uwp/getting-started, que hoje retorna para esta página, que por sua vez não possui qualquer informação sobre o uso de SQLite em aplicações UWP.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7ac57b24-45aa-e679-6ff9-5a25c369c1ff
* Version Independent ID: cc576199-b14c-a135-2291-cc48bf301b4e
* Content: [Introdução – EF Core](https://docs.microsoft.com/pt-br/ef/core/get-started/index?tabs=netcore-cli#feedback)
* Content Source: [entity-framework/core/get-started/index.md](https://github.com/aspnet/EntityFramework.Docs.pt-br/blob/live/entity-framework/core/get-started/index.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **avickers**

**Comment by srvbpigh** [comment]
Hello, @joaosantana
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Olá, @joaosantana,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/aspnet/EntityFramework.Docs/issues/2012.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
